version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    groups:
      dev-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5
